spring1843/go-dsa

- .github/workflows/pr-check.yaml
- README.md
* Add intro and table of contents to README.md
* Add Github workflow file for linting Go files and running tests
> Add Readme and lint check

- README.md
- bit/README.md
- complexity.md
- dnc/README.md
- dp/README.md
- graph/README.md
- hashtable/README.md
- heap/README.md
- linkedlist/README.md
- recursion/README.md
- strings/README.md
- tree/README.md
* consistent use of `we`, and `you`
* executable code in readme.md with output for graphs
* no sentences ending with adverbs
> consistency in usage of person, get rid of you and we

- tree/README.md
Corrected code link in readme for solution
> Tree Readme text change

- recursion/README.md
Make corrections to links in Readme file
> Recursion Readme text changes

- linkedlist/README.md
Corrected code link in readme file
> LinkedList Readme text changes

- hashtable/README.md
Corrected code links in readme file for hashtable
> Hashtable readme file changes

- graph/README.md
Corrected code links in readme
> Graph Readme text changes

- dp/README.md
Removed redundant text and corrected link for a code solution in readme file
> dynamic programming readme changes

- array/bubble_sort.go
Fixes: https://github.com/spring1843/go-dsa/issues/135
> More efficient bubble sort

- array/find_duplicate_in_array.go
- array/find_duplicate_in_array_test.go
* Add to the examples to clarify input is not sorted
* Use the absolute value of numbers to avoid negative index problems
> improve find duplicates problem description and tests

- array/README.md
> Wording: over was missing here

- array/add_two_numbers.go
Too much type conversion going on.
> Chore: remove type conversion overhead and math lib

- .github/pull-request-template.md
Fixes #N/A 
**What is being changed?**
Fix lint issue
**Why is this a good idea?**
**PR Opener Check List**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Fix lint issue

- .github/workflows/release.yaml
> fix setup go version

- .github/workflows/release.yaml
> add full path

- .github/cmd/pkg/cmd/export_md.go
- .github/cmd/pkg/cmd/root.go
- .github/cmd/pkg/problems/parse.go
- .github/cmd/pkg/problems/rehearsal.go
* Rename packages in each section to main so that they can be independently and easily executed.
* Add more flags for future needs
> Options for export-md command

- .github/cmd/pkg/cmd/export_md.go
- .github/cmd/pkg/problems/parse.go
- .github/workflows/release.yaml
- Makefile
Fixes the links in the exported md so that they link to the right tag in the repo.
> Fix links in release doc so they point to the repo with the right tag

- backtracking/README.md
* More details on implementation with an example
* Improved wording
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Add example to backtracking and more minor improvmeents

- .github/ISSUE_TEMPLATE/bug_report.md
Use headers instead of text in issues for more clarity
> move issue comments to headers

- array/README.md
- array/add_two_numbers_test.go
- array/bubble_sort_test.go
- array/equal_sum_subarrays_test.go
- array/find_duplicate_in_array_test.go
- array/insertion_sort_test.go
- array/product_of_all_other_elements_test.go
- array/reverse_inplace_test.go
- array/rotate_k_steps_test.go
- array/zero_sum_triplets_test.go
* Explain Bubble Sort and Insertion Sort
* Add more examples to Array rehearsal problems
* More clear wording in README.md
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> More details for array problems

- array/README.md
- strings/README.md
- strings/in_memory_database_test.go
- strings/longest_dictionary_word_test.go
- strings/longest_substring_test.go
- strings/look_and_tell_test.go
- strings/number_in_english_test.go
- strings/reverse_vowels_test.go
- strings/roman_numerals_test.go
<!-- Thank you for contributing ❤️
* Add examples and details for string problems
* Correct the notes on string complexity time and space
* Add note on strings.Builder and fmt.Sprintf
> Strings review

- linkedlist/README.md
- linkedlist/reverse_in_place_test.go
- linkedlist/serialization_test.go
Add clarifying examples to all linked-list questions.
> linked-list cleanup

- array/README.md
- linkedlist/README.md
- stack/README.md
- stack/balancing_symbols_test.go
- stack/basic_calculator_test.go
- stack/evaluate_postfix_test.go
- stack/infix_to_postfix_test.go
- stack/longest_valid_parentheses_test.go
- stack/max_stack_test.go
Add examples and more details for stacks.
> add stack details

- queue/symmetrical_binary_tree_test.go
Fix lint issues by formatting the binary tree diagram
> gofmt the binary tree diagram

- hashtable/README.md
- hashtable/cut_brick_wall_test.go
- hashtable/find_anagrams_test.go
- hashtable/max_points_on_line_test.go
- hashtable/missing_number_test.go
- hashtable/smallest_missing_positive_integer_test.go
- hashtable/sum_up_to_k_test.go
* Add examples to hash table problems
* Add diagram  to hash table section
> Add details to hash tables

- heap/README.md
- heap/heap_sort_test.go
- heap/k_closest_points_to_origin_test.go
- heap/kth_largest_element_test.go
- heap/median_in_a_stream_test.go
- heap/merge_sorted_list_test.go
- heap/regular_numbers_test.go
- heap/sliding_max_test.go
Add clarifying examples to problems in heap and improve the readme diagrams.
> Heap clarifying rehearsal problems
